# Deterministically assemble the final panel-level submission workbook.
# The input tables are generated by the upstream analysis modules and frozen
# here as typed, panel-specific submission tables for exact round-2 export.

suppressPackageStartupMessages({
  library(jsonlite)
  library(openxlsx)
})

input_dir <- file.path(paths$code, "submission_source_tables")
manifest_path <- require_file(file.path(input_dir, "manifest.json"), "supplementary-data manifest")
output_path <- Sys.getenv(
  "NPJAGING_SUPPLEMENTARY_OUTPUT",
  unset = file.path(project_root, "Supplementary_Data_1_round2.xlsx")
)

decode_cell <- function(token) {
  kind <- substr(token, 1L, 2L)
  payload <- substr(token, 3L, nchar(token))
  if (identical(kind, "N:")) return(NA)
  if (identical(kind, "B:")) return(identical(payload, "1"))
  if (identical(kind, "D:")) return(as.numeric(payload))
  if (identical(kind, "S:")) {
    payload <- gsub("\\\\n", "\n", payload)
    payload <- gsub("\\\\r", "\r", payload)
    payload <- gsub("\\\\t", "\t", payload)
    payload <- gsub("\\\\\\\\", "\\\\", payload)
    return(payload)
  }
  token
}

write_typed_block <- function(wb, sheet, path, start_row, expected_rows, expected_cols) {
  lines <- readLines(require_file(path, "supplementary-data table"), warn = FALSE)
  stopifnot(length(lines) == expected_rows + 1L)
  tokens <- lapply(lines[-1L], function(line) {
    tokens <- strsplit(line, "\t", fixed = TRUE)[[1L]]
    if (length(tokens) != expected_cols) {
      stop("Unexpected column count in ", path, call. = FALSE)
    }
    tokens
  })
  tokens <- do.call(rbind, tokens)
  for (j in seq_len(expected_cols)) {
    kinds <- substr(tokens[, j], 1L, 2L)
    runs <- rle(kinds)
    ends <- cumsum(runs$lengths)
    starts <- c(1L, head(ends, -1L) + 1L)
    for (k in seq_along(runs$values)) {
      idx <- starts[k]:ends[k]
      if (runs$values[k] == "N:") next
      values <- lapply(tokens[idx, j], decode_cell)
      if (runs$values[k] == "D:") values <- as.numeric(unlist(values))
      else if (runs$values[k] == "B:") values <- as.logical(unlist(values))
      else values <- as.character(unlist(values))
      writeData(
        wb, sheet, values, startRow = start_row + starts[k] - 1L,
        startCol = j, colNames = FALSE, rowNames = FALSE, keepNA = FALSE
      )
    }
  }
}

as_rows <- function(x) {
  if (is.null(x) || !length(x)) integer()
  else as.integer(unlist(x, use.names = FALSE))
}

manifest <- fromJSON(manifest_path, simplifyVector = FALSE)
manifest <- manifest[order(vapply(manifest, function(x) x$order, numeric(1)))]
wb <- createWorkbook(creator = "npj Aging analysis workflow")

source_style <- createStyle(
  fgFill = "#D9EAF7", textDecoration = "bold", fontColour = "#1F1F1F",
  valign = "center", wrapText = TRUE, border = "Bottom", borderColour = "#9FBAD0"
)
description_style <- createStyle(
  textDecoration = "italic", fontColour = "#555555", fontSize = 9,
  valign = "center", wrapText = TRUE
)
header_style <- createStyle(
  fgFill = "#1F4E78", textDecoration = "bold", fontColour = "#FFFFFF",
  fontSize = 9, halign = "center", valign = "center", wrapText = TRUE,
  border = "Bottom", borderColour = "#17365D"
)

for (spec in manifest) {
  sheet <- spec$sheet
  message("Exporting ", sheet)
  addWorksheet(wb, sheet, gridLines = FALSE)
  freezePane(wb, sheet, firstActiveRow = min(5L, spec$rows + 1L))

  blocks <- spec$blocks
  if (!is.list(blocks[[1L]])) blocks <- list(blocks)
  for (block in blocks) {
    write_typed_block(
      wb, sheet, file.path(input_dir, block$file), as.integer(block$start_row),
      as.integer(block$rows), as.integer(block$cols)
    )
  }

  source_rows <- as_rows(spec$source_rows)
  description_rows <- as_rows(spec$description_rows)
  header_rows <- as_rows(spec$header_rows)
  if (length(source_rows)) {
    addStyle(wb, sheet, source_style, rows = source_rows, cols = seq_len(spec$cols), gridExpand = TRUE)
    setRowHeights(wb, sheet, rows = source_rows, heights = 24)
  }
  if (length(description_rows)) {
    addStyle(wb, sheet, description_style, rows = description_rows, cols = seq_len(spec$cols), gridExpand = TRUE)
    setRowHeights(wb, sheet, rows = description_rows, heights = 30)
  }
  if (length(header_rows)) {
    addStyle(wb, sheet, header_style, rows = header_rows, cols = seq_len(spec$cols), gridExpand = TRUE)
    setRowHeights(wb, sheet, rows = header_rows, heights = 34)
  }
  setColWidths(wb, sheet, cols = 1L, widths = 24)
  if (spec$cols >= 2L) setColWidths(wb, sheet, cols = 2L, widths = 44)
  if (spec$cols >= 3L) setColWidths(wb, sheet, cols = 3L:spec$cols, widths = 16)

  if (spec$order > 56L) {
    if (length(source_rows)) setRowHeights(wb, sheet, rows = source_rows, heights = 42)
    if (length(description_rows)) setRowHeights(wb, sheet, rows = description_rows, heights = 54)
  }
  if (identical(sheet, "README")) {
    setColWidths(wb, sheet, cols = 1L, widths = 30)
    setColWidths(wb, sheet, cols = 2L, widths = 110)
  } else if (identical(sheet, "Initial_file_mapping")) {
    setColWidths(wb, sheet, cols = 1:4, widths = c(30, 34, 48, 68))
  } else if (grepl("_membership$", sheet)) {
    setColWidths(wb, sheet, cols = 1:4, widths = c(46, 14, 72, 72))
    mergeCells(wb, sheet, cols = 2:4, rows = 1)
    mergeCells(wb, sheet, cols = 2:4, rows = 2)
  }
}

dir.create(dirname(output_path), recursive = TRUE, showWarnings = FALSE)
saveWorkbook(wb, output_path, overwrite = TRUE)
message("Saved ", normalizePath(output_path, mustWork = FALSE))
