# Update final source-data workbook sheets that depend on the participant-aware
# Moller-Levet sleep-restriction analysis. This runs after the staged outputs are
# generated by 01c_propagate_participant_aware_moller_levet_dependencies.R.

if (!exists("paths")) {
  args <- commandArgs(FALSE)
  file_arg <- sub("^--file=", "", args[grepl("^--file=", args)][1])
  script_dir <- if (!is.na(file_arg)) dirname(normalizePath(file_arg, mustWork = FALSE)) else getwd()
  project_root_guess <- normalizePath(file.path(script_dir, "..", "..", ".."), mustWork = FALSE)
  Sys.setenv(NPJAGING_PROJECT_ROOT = Sys.getenv("NPJAGING_PROJECT_ROOT", unset = project_root_guess))
  source(file.path(dirname(script_dir), "config.R"))
}

suppressPackageStartupMessages({
  library(openxlsx)
  library(readr)
  library(dplyr)
  library(stringr)
  library(purrr)
})

stage_dir <- file.path(paths$tables, "participant_aware_staging")
workbook_path <- file.path(project_root, "Supplementary_Data_1_full_analysis_outputs.xlsx")
backup_path <- file.path(project_root, "Supplementary_Data_1_full_analysis_outputs.pre_participant_aware_backup.xlsx")
require_file(workbook_path, "final Supplementary Data 1 workbook")
require_file(stage_dir, "participant-aware staged tables")

if (!file.exists(backup_path)) {
  file.copy(workbook_path, backup_path, overwrite = FALSE)
}

read_stage <- function(file, cols = NULL) {
  dat <- read_csv(file.path(stage_dir, file), show_col_types = FALSE)
  if (!is.null(cols)) dat <- dat %>% select(any_of(cols))
  dat
}

make_matrix <- function(source_label, description, dat) {
  dat <- as.data.frame(dat, stringsAsFactors = FALSE)
  width <- max(1, ncol(dat))
  top <- matrix(NA, nrow = 2, ncol = width)
  top[1, 1] <- source_label
  top[2, 1] <- description
  headers <- matrix(names(dat), nrow = 1)
  values <- as.matrix(dat)
  rbind(top, headers, values)
}

hsf_related <- function(gene) {
  str_detect(as.character(gene), regex("HSF|HSP|DNAJ|BAG|CCT|CANX|CALR|FKBP|PSM|TCP|CHORDC|HSPA|HSPD|HSPH|HSPB", ignore_case = TRUE))
}

make_sf4e_matrix <- function() {
  summary <- read_stage("SF4e_participant_aware_SRdown_x_AgingDown_fisher_summary.csv")
  genes <- read_stage(
    "SF4e_participant_aware_JenAge_SRnominalP05_AgeDirection_overlap_genes.csv",
    c(
      "gene",
      "participant_aware_phase_logFC",
      "participant_aware_phase_p",
      "participant_aware_phase_FDR",
      "delta_mesor",
      "mesor_p",
      "mesor_FDR",
      "age_logFC_per_decade",
      "age_p",
      "age_FDR"
    )
  ) %>%
    mutate(hsf_related = hsf_related(gene))

  primary <- summary %>%
    filter(dataset == "JenAge", sr_threshold == "sr_nominalP05", aging_threshold == "age_direction_down") %>%
    mutate(
      hsf_related_overlap_n = sum(genes$hsf_related, na.rm = TRUE),
      hsf_related_overlap_genes = paste(genes$gene[genes$hsf_related], collapse = ";")
    )

  width <- max(ncol(primary), ncol(genes))
  pad_df <- function(dat) {
    if (ncol(dat) < width) {
      for (i in seq_len(width - ncol(dat))) dat[[paste0("blank_", i)]] <- NA
    }
    dat
  }
  top <- matrix(NA, nrow = 7, ncol = width)
  top[1, 1] <- "Source: SF4e_participant_aware_SRdown_x_AgingDown_fisher_summary.csv"
  top[2, 1] <- "Participant-aware SR-down x healthy-blood aging-down Venn/Fisher statistics plotted in Supplementary Fig. 4e"
  top[3, seq_len(ncol(primary))] <- names(primary)
  top[4, seq_len(ncol(primary))] <- as.character(primary[1, ])
  top[5, 1] <- "Source: SF4e_participant_aware_JenAge_SRnominalP05_AgeDirection_overlap_genes.csv"
  top[6, 1] <- "Full participant-aware human blood SR-down x healthy-blood aging-down convergence gene list plotted in Supplementary Fig. 4e"
  top[7, seq_len(ncol(genes))] <- names(genes)
  rbind(top, as.matrix(pad_df(genes)))
}

sheet_specs <- list(
  F1d = list(
    file = "F1d_participant_aware_source_data.csv",
    source = "Source: F1d_participant_aware_source_data.csv",
    description = "Phase-aligned representative gene expression time courses plotted in Fig. 1d; inferential statistics from participant-aware limma duplicateCorrelation block=subject model."
  ),
  F1e = list(
    file = "F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    source = "Source: F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    description = "Participant-aware Reactome module MESOR-like effects, matched null intervals, empirical p values, and FDR values plotted in Fig. 1e."
  ),
  SF1a = list(
    file = "SF1a_participant_aware_source_data.csv",
    source = "Source: SF1a_participant_aware_source_data.csv",
    description = "Representative SR time-course profiles plotted in Supplementary Fig. 1a; inferential statistics from participant-aware model."
  ),
  SF1b = list(
    file = "SF1b_participant_aware_reactome_wide_MESOR_ranking.csv",
    source = "Source: SF1b_participant_aware_reactome_wide_MESOR_ranking.csv",
    description = "Participant-aware Reactome-wide MESOR-like ranking plotted in Supplementary Fig. 1b."
  ),
  SF1c = list(
    file = "F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    source = "Source: F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    description = "Participant-aware predefined module rhythmic-amplitude values plotted in Supplementary Fig. 1c."
  ),
  SF1d = list(
    file = "F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    source = "Source: F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    description = "Participant-aware predefined module acrophase values plotted in Supplementary Fig. 1d."
  ),
  SF1e = list(
    file = "F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    source = "Source: F1e_SF1c_SF1d_SF1e_participant_aware_selected_reactome_modules.csv",
    description = "Participant-aware matched random-set MESOR comparison plotted in Supplementary Fig. 1e."
  ),
  SF4f = list(
    file = "SF4f_SF4g_participant_aware_JenAge_SRnominalP05_AgeDirection_Reactome_ORA.csv",
    source = "Source: SF4f_SF4g_participant_aware_JenAge_SRnominalP05_AgeDirection_Reactome_ORA.csv",
    description = "Participant-aware Reactome pathway-gene network enrichment table plotted in Supplementary Fig. 4f."
  ),
  SF4g = list(
    file = "SF4g_participant_aware_Reactome_family_summary.csv",
    source = "Source: SF4g_participant_aware_Reactome_family_summary.csv",
    description = "Participant-aware collapsed Reactome pathway-family enrichment plotted in Supplementary Fig. 4g."
  )
)

wb <- loadWorkbook(workbook_path)
original_order <- names(wb)

title_style <- createStyle(textDecoration = "bold", fgFill = "#D9EAF7")
note_style <- createStyle(fgFill = "#F3F6FA")
header_style <- createStyle(textDecoration = "bold", fgFill = "#EDEDED")

replace_sheet <- function(wb, sheet, mat) {
  if (sheet %in% names(wb)) removeWorksheet(wb, sheet)
  addWorksheet(wb, sheet, gridLines = FALSE)
  writeData(wb, sheet, mat, colNames = FALSE, rowNames = FALSE, keepNA = FALSE)
  addStyle(wb, sheet, title_style, rows = 1, cols = seq_len(ncol(mat)), gridExpand = TRUE, stack = TRUE)
  addStyle(wb, sheet, note_style, rows = 2, cols = seq_len(ncol(mat)), gridExpand = TRUE, stack = TRUE)
  addStyle(wb, sheet, header_style, rows = 3, cols = seq_len(ncol(mat)), gridExpand = TRUE, stack = TRUE)
  freezePane(wb, sheet, firstActiveRow = 4)
  setColWidths(wb, sheet, cols = seq_len(ncol(mat)), widths = "auto")
  invisible(wb)
}

for (sheet in names(sheet_specs)) {
  spec <- sheet_specs[[sheet]]
  dat <- read_stage(spec$file)
  replace_sheet(wb, sheet, make_matrix(spec$source, spec$description, dat))
}
replace_sheet(wb, "SF4e", make_sf4e_matrix())

worksheetOrder(wb) <- match(original_order, names(wb))
saveWorkbook(wb, workbook_path, overwrite = TRUE)

check <- loadWorkbook(workbook_path)
stopifnot(identical(names(check), original_order))

audit <- tibble(
  sheet = c(names(sheet_specs), "SF4e"),
  rows = map_int(c(names(sheet_specs), "SF4e"), ~ nrow(read.xlsx(workbook_path, sheet = .x, colNames = FALSE))),
  cols = map_int(c(names(sheet_specs), "SF4e"), ~ ncol(read.xlsx(workbook_path, sheet = .x, colNames = FALSE))),
  updated_from_participant_aware_model = TRUE
)
write_csv(audit, file.path(stage_dir, "supplementary_workbook_participant_aware_update_audit.csv"))
message("Updated participant-aware sheets in ", workbook_path)
